_BASE_: r50.yaml
MODEL:
  # WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  WEIGHTS: "model/weights/model_final_4e9874.pkl"
  SEM_SEG_HEAD:
    IGNORE_VALUE: 65
    NUM_CLASSES: 65
  MASK_FORMER:
    # BACKUP_TOKEN: True
    BACKUP_TOKEN: False
    # DEPTH_DECODER: True
    DEPTH_DECODER: False
    # TRAIN_DEPTH: True
    TRAIN_DEPTH: False
    # TRANSFER_CITYSCAPES: True
    TRANSFER_MV: True
    TEST:
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.0
DATASETS:
  TRAIN: ("mapillary_vistas_panoptic_train",)
  # TEST: ("mapillary_vistas_panoptic_val",)
  # TRAIN: ("semkitti_dvps_train",)
  TEST: ("semkitti_dvps_val",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0001
  MAX_ITER: 100000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  # MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 2048) for x in range(5, 21)]"]
  MIN_SIZE_TRAIN: (1024, 1280, 1536, 1792, 2048)
  # MIN_SIZE_TRAIN: (640, 704, 768, 832, 896, 960, 1024)
  MAX_SIZE_TRAIN: 8192
  # MIN_SIZE_TRAIN: (388, 422, 460, 480, 576, 614, 652, 692, 730, 768)
  # MAX_SIZE_TRAIN: 2800
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  # MIN_SIZE_TEST: 2048
  # MAX_SIZE_TEST: 2048
  MIN_SIZE_TEST: 384
  MAX_SIZE_TEST: 1280
  CROP:
    ENABLED: True
    TYPE: "absolute"
    # SIZE: (1024, 1024)
    SIZE: (384, 1280)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  # SIZE_DIVISIBILITY: 1024 # used in dataset mapper
  SIZE_DIVISIBILITY: 1280 # used in dataset mapper
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_panoptic_mv"
TEST:
  EVAL_PERIOD: 5
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
VERSION: 2
OUTPUT_DIR: "./output/mv/1"
