MODEL:
  META_ARCHITECTURE: "PanopticFCN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [1.0, 1.0, 1.0]
  MASK_ON: True
  VIS_PERIOD: 1000
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "BN" #"SyncBN"
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  LOSS_WEIGHT:
    SEGMENT: 4.0
  POSITION_HEAD:
    DEFORM: False
    THING:
      NUM_CLASSES: 8
      THRES: 0.01
      TOP_NUM: 200
    STUFF:
      THRES: 0.1
      NUM_CLASSES: 19
  SEM_SEG_HEAD:
    NUM_CLASSES: 19
  KERNEL_HEAD:
    DEFORM: False
    INSTANCE_SCALES: ((1, 128), (64, 256), (128, 512), (256, 1024), (512, 2048),)
  TENSOR_DIM: 150 # Adapted because max inst. per img > 100
  FEATURE_ENCODER:
    DEFORM: False
  INFERENCE:
    INST_THRES: 0.5
    SIMILAR_THRES: 0.97
    COMBINE:
      STUFF_AREA_LIMIT: 2048
DATASETS:
  # TRAIN: ("cityscapes_fine_panoptic_train_separated",)
  TRAIN: ("cityscapes_fine_panoptic_train1",)
  TEST: ("cityscapes_fine_panoptic_val_separated",)
SOLVER:
  OPTIMIZER: "ADAM"
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.0001
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  POLY_LR_POWER: 0.9
  WARMUP_ITERS: 2000
  WARMUP_FACTOR: 0.001
  WARMUP_METHOD: "linear"
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 35.0
  IMS_PER_BATCH: 2
  MAX_ITER: 60000
  CHECKPOINT_PERIOD: 10000
INPUT:
  # MIN_SIZE_TRAIN: (512, 768, 1024, 1152, 1216, 1344, 1408, 1536, 1664, 1728, 1856, 1920, 2048)
  MIN_SIZE_TRAIN: (1024, 1024)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MAX_SIZE_TRAIN: 4096
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 2048
  CROP:
    # ENABLED: True
    ENABLED: False
    TYPE: "absolute"
    SIZE: (512, 1024)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  COLOR_AUG: False
  MASK_FORMAT: "bitmask"
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
TEST:
  EVAL_PERIOD: 10000
CUDNN_BENCHMARK: True
VERSION: 2
OUTPUT_DIR: "./output/test"
